version: "3"

services:
    game-engine:
        image: coderone.azurecr.io/bomberland-engine:2381
        volumes:
            - type: "bind"
              source: ./bomberman/replay.json
              target: /app/replay.json

    agent:
        build:
            context: bomberman
            dockerfile: Dockerfile.agent
        volumes:
            - ./bomberman:/app
